# Generated by Django 3.1.2 on 2020-11-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='complete',
            field=models.BooleanField(default=True),
        ),
    ]
