# Generated by Django 3.1.2 on 2020-11-11 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20201112_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='complete',
        ),
    ]
